spring.application.name=birdmail

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/birdmail
spring.datasource.dbname=birdmail
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
