spring.application.name=birdmail

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/birdmail
spring.datasource.dbname=birdmail
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

#juwt signature
jwt.secret=X7mP9vL2qR8nK4tY1wE6uI3oA5sD7fG9H2jC8bN4mQ1zT6xV
